spring.application.name=shoppySaga

server.port=8085

#Eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#ConfigServer
spring.config.import=optional:configserver:http://localhost:8888