spring.application.name=shoppyGateway
server.port=8081
jwt.secret=HelloLearnersWorkForVictoryStartingShoppyApplicationusingJava17.0.4withPID63786

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
